In [ ]:
%pip install numpy

In [2]:
import numpy as np

In [8]:
list1 = [1, 2, 3, 4]
list2 = [5, 6, 7, 8]

#print ((list1*list2)) # this isn't possible. Have to go through each individual index (lengthy process! hence np)
print (list1[0]*list2[0])
print (list1[3]+list2[3])

5
12


In [15]:
#Task 1: Create a 1d array of numbers from 1:9
list_py = [1, 2, 3, 4, 5, 6, 7, 8, 9] #to use arrays in python you have to import a library like numpy. This is showing a list. 
print(list_py)

list1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


In [49]:
#Task 2: Create a 3x3 numpy array of all Boolean value trues
#step 1 - creating 3x3 array
arr2 = np.ones(9)
print(arr2) #this prints them all in one row. Next need to reshape them
new_arr2 = arr2.reshape(3,3)
print(new_arr2)

#or, create it from scratch as a 3x3
arr_3x3 = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
print (arr_3x3)

# or, like this: 
arr4 = np.ones([3,3])
print(arr4)

# Step 2, get it to show as Boolean value true. 
arr5 = np.ones([3,3], dtype=bool) #this puts it in data type Boolean. 
print(arr5)


[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [62]:
# Task 3: Extract all odd numbers from an array 1:10
task3 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print (task3)
# for x in task3:
#         if x%2 != 0:
#             print (x) #this gives it with each integer on a new line. 


new_list3 = [x for x in task3 if x%2 !=0]
print(new_list3) #this gives it as a new list. 


[ 1  2  3  4  5  6  7  8  9 10]
[1, 3, 5, 7, 9]


In [87]:
#Task 4: Replace all odd numbers in an array of 1-10 with the value -1
task4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

for x in range(len(task4)):
    if x%2 != 1:
        task4[x] = -1
print(task4)

# wherever there is x/2 with a remainder of 1, assign x the value of -1. 
#Print list.

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [88]:
#Task 5: Convert a 1D array to a 2D array with 2rows
task5 = np.ones (4)
print(task5)
new_task5 = task5.reshape(2, 2)
print(new_task5)

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]]


In [100]:
# Task 6: Create two arrays a and b, stack these two arrays vertically, use the np.dot and np.sum to calculatetotals
arrA = np.array([1, 2, 3, 4])
arrB = np.array([5, 6, 7, 8,])

arrC = (arrA+ arrB) #this gives the sum of each column as a new list. 
print (arrC)

arrC2 = np.dot(arrA, arrB) #this gives the sum of values in the same positions multiplied, then added up. e.g. (1*5)+(2*6)+(3*7)+(4*8)=70.
print(arrC2)

sum = np.sum(arrC2)
print(sum) #this is giving the same result as above, is that because it's 1d array? Yes. need to reshape them into a matrix, see below.

[ 6  8 10 12]
70
70


In [111]:
#Task 6 re-run

arrD = np.array([1, 2, 3, 4]).reshape (2,2)
arrE = np.array([5, 6, 7, 8]).reshape (2,2)

print (arrD)
print (arrE)
print ("Below here the .dot and .sum begins")

arrF = np.dot(arrD, arrE) #[R2*C1, R1*C2],[R2*C1, R2*C2]
print(arrF)

sum = np.sum(arrF)
print(sum)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Below here the .dot and .sum begins
[[19 22]
 [43 50]]
134


In [17]:
#Extension Task 1
# create the following : [1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3,] This must be using a math function?

a = np.array([2, 2, 2, 3, 3, 3, 4, 4, 4, 2, 3, 4, 2, 3, 4, 2, 3, 4])
print(a)
print("Subtract :", a -1) #note - don't put a comma between the 'a' and the math funciton


[2 2 2 3 3 3 4 4 4 2 3 4 2 3 4 2 3 4]
Subtract : [1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]
